version: '3.7'

services:
  reactapp:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: 'true'
