export const GET_CATEGORIES = 'GET_CATEGORIES';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
